language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  - secure: L/w7XsL4YR9YClSZhpnfayzL+gNVfw0375KILe9ZPc9cLUrOSaa0gxjVip2z4p4iG2ApyYVOXUGe71B37xcwI+hJu9sA7lXVrJtIyWGIpE+ogyKBT2TWTSgEVv6eOaJNjFnObufOVPUcgpL/6eNaTsI5DqsALEirNoJOfmMb2NStyXijpzL49w9KezbIz3tAENCInKWrk9rb17AnHJU0WjrJOZSCeMcdR5K+wTBVg5775GpkLICs6lBDqyo7Z27QnAduadt8KXnpnpE2zTnIBIg2m1FL6UIkjJ2tYN/QIHygVq79W34j6T6L7r01+LTdIPC5/ANqdj3mTopI8Kx6v97n20yidv+DeBh9vICsFgREyWQzwHo8wFDRbs+Tt08qgHh5yLQN4RMSpX6iy0R5N0J5p9j+qwLfPeCDOKKvLSqxfKAAwnudKMHuew2SdisyDW0in7wada21NyG7eGa0V+HKyYeEP/yRMWsALr/etMCU9tRCGuC4vjnm/XCc0CsmZ8s0HozoycBExc3NRH1aTnCG7VC6jhYltODOJRSW9NdRbPCbTM/wniKeqjcAeb/U2USIiaQPGqADLVaJGoJVRL0b7FlBr2NRHi3W57DOnYgQOTK7PfYZgj+vv18VD4BVHiKRTXOsVIbYNmY5S76bzy0XdZAhCEYu7RGPzHz/YQo=
  - secure: qpWNNR4fy1FKob1YMid0RR0QmgN/rYNft3SS8kG+UGGocfXQlet5zpTw0ERC0IDhzzq/wAh5QjWu/XBBfycMPfZCo1X0ORW+87DrPwrAXxQQtjr5BY6W1CaV2jBuJgKEet1js6nkec68DfPJbMXNDdaayapBvi3N6AiNNylXlrZ/BK/XJhOD7vUQ1huHOHNGZrQn2sGXQ2qhlBLFD+R4aEmFEi4xoqC5Ekleh41au93UhUXas0ck3DFW/7CcodBB9BNv50h/sOxsH/4RZkRR6i7H0oim6eANSdZ+1Mnz/BoOphi5cfmOHh6yYY3IvIu5R4xHhhTlUclXU8826mdjnLHtd8m9fmK7ZvnN2Puy2DU8ErT1Or8rkH4TAKdrekANVCplmZyNdO6wp4bgyPkqyVtxavkhQa9GttPnsRi/oeOUcjVUNLVDzKTDczZbep8BGewUZErE0mOubsTA69dQMkrZD61q6BaXWGYV2OH/RnjeLcZfA2IVQwQQQdRRiqJFh4K3xi+JRf2eGBdNd+u3Aoov8PlAtj4whvfV8dKPLbAXF1Ig/nU+r9Y9eFSmU50RlwFMbD4BxWFiR6W4pB1O/SfoZPMZN4wrV5AACmx+2n2yI+yub9+UZ/uFuu8MaUfQSPmJbGYcomnQoSobeEJcXMuV4AJQS815u0OOJ6TmUMI=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
